services:
  database:
    image: mariadb
    environment:
      MARIADB_PASSWORD: pass
      MARIADB_USER: user
      MARIADB_ROOT_PASSWORD: rootpass
    ports:
      - 3305:3306
    volumes:
      - database_data:/var/lib/mysql:rw
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - default
    depends_on:
      - database
  mspr-501:
    build: .
    ports:
      - 212.132.121.24:3000:3000
    networks:
      - default
    depends_on:
      - database

volumes:
  database_data:

networks:
  default:
    external:
      name: mspr-501_network