name: CI/CD

on:
  push:
    branches:
      - main  # Or your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /root/websites/mspr-501/
            git pull

            docker-compose down --remove-orphans --volumes

            docker network remove mspr-501_network

            docker network create mspr-501_network 

            docker-compose -f docker-compose.prod.yml up -d

            docker exec mspr-501-mspr-501-1 npx prisma migrate dev
          